### PR TITLE
feat: add credential_type plugin config

### LINKED ISSUE #146: authentication issues
trying to integrate into the GH actions pipeline I'm getting the following:

> Error: describe-key command failed: ERROR: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: Tenant shouldn't be specified for managed identity account

I'm seeing in the code its using DefaultAzureCredential and, somehow, fails at the cli auth. I do use `az login --identity --username xyz` for managed identity login and the agent itself is also capable of doing OIDC auth, yet somehow it still fails.

to clarify: az acr login works in the same job and i can succesfully push to the acr

Also looking at the code there appears to be no way to tweak the way you login (or pass existing token)

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Feat:
- added creential_type plugin config key
- supported credential type: default, environment, managedidentity, azurecli

Test:
- unit test cases
- e2e test cases
- tested environment credential, workload identity credential, managed identity in pod of AKS
- tested Azure cli credential locally

Resolves #146 #154 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Comment by Two-Hearts** [comment]
So before this PR, i.e., before adding plugin config `credential_type`, how does a Notation user specify their `credential_type`?

**Comment by JeyJeyGao** [comment]
> So before this PR, i.e., before adding plugin config `credential_type`, how does a Notation user specify their `credential_type`?

through this flag: --plugin-config credential_type=xxxx

**Comment by Two-Hearts** [comment]
I'm a bit confused, `added credential_type plugin config key` means this key is added in this PR right? My question is what's the behavior BEFORE this PR?

**Comment by JeyJeyGao** [comment]
> I'm a bit confused, `added credential_type plugin config key` means this key is added in this PR right? My question is what's the behavior BEFORE this PR?

Before this PR, users could not set credential_type; it was chosen automatically by the library.
https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM. Is the plugin config `credential_type` documented anywhere?

**Comment by JeyJeyGao** [comment]
> LGTM. Is the plugin config `credential_type` documented anywhere?

Added documents.

**Pull request merged**
